### ISSUE TITLE
Icones notícias faltando

### ISSUE THREAD

**Issue by Atzingen** [Atzingen/CEPAD-www#13]
Tem algum icone que não está carregando no nome e data da notícia. Só tirar ou colocar algum icone tipo fonts-awsome 
![Captura de tela 2022-11-01 162901](https://user-images.githubusercontent.com/6025239/199321620-10611864-17c1-455a-87ce-5d0be32b7d54.png)

**Comment by larissamazzero** [comment]
![image](https://user-images.githubusercontent.com/105591958/200072577-17a03e07-4a7e-4b5a-b312-f887b68eb160.png)
feito
