### ISSUE TITLE
usar base.html como padrão

### ISSUE THREAD

**Issue by Atzingen** [Atzingen/CEPAD-www#17]
Todas as páginas devem usar a parte de header, navbar e footer importados do base.html. Algumas coisas estão repetidas nas páginas isoladas, deixando muito código nelas para analisar. Manter os itens acima apenas no base e tirar o código desnecessário das outras páginas

**Comment by larissamazzero** [comment]
Prof, eu já tinha feito isso, a única página que tem coisas a mais é o home, pois a header dele é diferente dos demais. A parte dos "breadcrumbs", como é chamado lá no template é diferente para todos, por isso mantive.

**Comment by Atzingen** [comment]
Já resolvido pela @larissamazzero
